export const SET_PLAYERS = 'SET_PLAYERS';
export const ADD_PLAYER = 'ADD_PLAYER';
export const DELETE_PLAYER = 'DELETE_PLAYER';
export const ADD_PLAYER_START = 'ADD_PLAYER_START';
export const DELETE_PLAYER_START = 'DELETE_PLAYER_START';

export const SET_GAMES = 'SET_GAMES';
export const ADD_GAME = 'ADD_GAME';
export const ADD_GAME_START = 'ADD_GAME_START';
export const DELETE_GAME = 'DELETE_GAME';
export const DELETE_GAME_START = 'DELETE_GAME_START';

export const SET_GAME_SESSIONS = 'SET_GAME_SESSIONS';
export const FETCH_DATA_START = 'FETCH_DATA_START';
export const ADD_GAME_SESSION = 'ADD_GAME_SESSION';
export const DELETE_GAME_SESSION = 'DELETE_GAME_SESSION';
export const ADD_GAME_SESSION_START = 'ADD_GAME_SESSION_START';
export const DELETE_GAME_SESSION_START = 'DELETE_GAME_SESSION_START';
